apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gpi-app
  template:
    metadata:
      labels:
        app: gpi-app
    spec:
      containers:
        - name: gpi-app
          image: mayuresh23/gpi-devops-app
          ports:
            - containerPort: 8080
